# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bea491c4d32a59f9370e6e79cd80efda251ad6fe2f4c7572fd5f71cac7cd4e8ae56f511ccac2261826c9bcf7cc9d97cc4c34bcc43337f4842d6fedc35c3c098d

test:
  secret_key_base: c39e290daf92cc7de115606565c20ba1277cff76708b5017fe0a059cefa746204a47508595bad6072736b08b1f2fc3bbfdeb63f89e03e0efbf14da8d5cc930de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
